CREATE TABLE [dbo].[posts]
(
	PostID INT IDENTITY(0,1) NOT NULL PRIMARY KEY,
	Title VARCHAR(128) NOT NULL,
	Body VARCHAR(512) NOT NULL,
	[Like] INT NULL,
	UserID INT NOT NULL,
	[Datetime] DATETIME NOT NULL
)
